import json
import os

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Define master rule (forces Snakemake to generate all missing files)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

with open("../../data_spec/lcl_proc_spec.json", "r") as f:
    dirs = json.load(f)
    WORKDIR = dirs["WORKDIR"]
    DATADIR = dirs["DATADIR"]
    RAWDIR = dirs["RAWDIR"]
    REFDIR = dirs["REFDIR"]
    FOLDS = 10

fold_assignments = "../data_fold_assignments.csv"

with open("../../data_spec/procap_to_1k_genomes.json", "r") as handle:
    prefix_converter = json.load(handle)
with open("../../data_spec/missing_1k_genomes.txt", "r") as handle:
    missing = handle.read().splitlines()
nonempty_procap_prefixes = [
    prefix
    for prefix in prefix_converter.keys()
    if prefix_converter[prefix] not in missing
]

output = expand(
    os.path.join(DATADIR, "procap/individual_windows_mean/{prefix}.{pm}.{fold}.csv.gz"),
    prefix=nonempty_procap_prefixes,
    pm=["pl", "mn"],
    fold=range(FOLDS),
)
output_npz = expand(
    os.path.join(DATADIR, "final_data_folds/concat_mean_procap_{tail}.npz"),
    tail=range(FOLDS),
)


rule procap_all:  # A master rule that ensures all the other rules run
    input:
        output,
        output_npz,
    params:
        os.path.join(WORKDIR, "procap"),
    shell:
        "echo rm -r {params}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Convert bw files to hg38
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule unpack_procap:
    input:
        os.path.join(DATADIR, "procap/bigwig/merged_{pm}_rpm.bw"),
    output:
        os.path.join(WORKDIR, "procap/bigwig/merged_{pm}_rpm.bw"),
    resources:
        load=1,
    shell:
        "cp {input} {output}"


rule unpack_windows:
    input:
        windows=os.path.join(DATADIR, "procap/windows/{prefix}_window_uniq.bed.gz"),
    output:
        windows=os.path.join(WORKDIR, "procap/windows/{prefix}_window_uniq.bed"),
    resources:
        load=1,
    shell:
        "zcat {input} > {output}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Get signal from each window
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_get_signal:
    input:
        windows=os.path.join(WORKDIR, "procap/windows/{prefix}_window_uniq.bed"),
        bw=os.path.join(WORKDIR, "procap/bigwig/merged_{pm}_rpm.bw"),
    output:
        os.path.join(WORKDIR, "procap/windows/signal/{prefix}.{pm}.txt.gz"),
    resources:
        load=1,
    params:
        os.path.join(WORKDIR, "procap/windows/signal/{prefix}.{pm}.txt"),
    shell:
        """
        bwtool extract bed {input} {params}
        gzip {params}
        """


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Convert signal files to csv (easy to read)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_read_signal:
    input:
        os.path.join(WORKDIR, "procap/windows/signal/{prefix}.{pm}.txt.gz"),
    output:
        os.path.join(WORKDIR, "procap/windows/signal/{prefix}.{pm}.csv.gz"),
    resources:
        load=1,
    shell:
        "python ../../data_processing_scripts/read_signal.py {input} | gzip > {output}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Split signal files into train, val, and test
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_split_signal:
    input:
        os.path.join(WORKDIR, "procap/windows/signal/{prefix}.{pm}.csv.gz"),
    output:
        fold=os.path.join(
            DATADIR, "procap/individual_windows_mean/{prefix}.{pm}.{fold}.csv.gz"
        ),
    resources:
        load=1,
    params:
        fold_assignments=fold_assignments,
        fold="{fold}",
    run:
        import pandas as pd

        fold_assignments = pd.read_csv(
            params.fold_assignments, header=0, index_col=None
        )
        chroms = list(
            fold_assignments[fold_assignments["fold"] == int(params.fold)].chrom
        )
        data = pd.read_csv(input[0], header=None, index_col=0)
        fold = pd.DataFrame(
            [data.loc[idx] for idx in data.index if idx.split(":")[0] in chroms]
        )
        fold.to_csv(output[0], header=False, index=True, compression="gzip")


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Concatenate data between individuals
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_concat:
    input:
        [
            os.path.join(DATADIR, "procap/individual_windows_mean/%s.{pm}.{fold}.csv.gz")
            % prefix
            for prefix in nonempty_procap_prefixes
        ],
    output:
        os.path.join(WORKDIR, "procap/concat/concat_{pm}_{fold}.csv.gz"),
    resources:
        load=1,
    shell:
        "zcat {input} | gzip > {output}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Replace window coords with index #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_idx_csv:
    input:
        os.path.join(WORKDIR, "procap/concat/concat_{pm}_{fold}.csv.gz"),
    output:
        os.path.join(WORKDIR, "procap/concat/idx/concat_{pm}_{fold}.csv.gz"),
    resources:
        load=1,
    shell:
        "zcat {input} | bash ../../data_processing_scripts/idx_csv.sh | gzip > {output}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Join pl and mn strand signal
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_join_strands:
    input:
        pl=os.path.join(WORKDIR, "procap/concat/concat_pl_{fold}.csv.gz"),
        mn=os.path.join(WORKDIR, "procap/concat/concat_mn_{fold}.csv.gz"),
    output:
        os.path.join(WORKDIR, "procap/final/concat_mean_procap_{fold}.npz"),
    resources:
        load=25,
    shell:
        "python ../../data_processing_scripts/join_signal.py {input} --in_csv {output}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Clean up scratch space
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule procap_move_back:
    input:
        os.path.join(WORKDIR, "procap/final/concat_mean_procap_{tail}.npz"),
    output:
        os.path.join(DATADIR, "final_data_folds/concat_mean_procap_{tail}.npz"),
    resources:
        load=1,
    shell:
        "cp {input} {output}"
